#version: '1.0.2.{build}'
version: '1.0.2.{build}'
image: Visual Studio 2017
configuration: Release
dotnet_csproj:
  patch: true
  file: 'src\FluentCast\FluentCast.csproj'
  version: $(appveyor_build_version)
  package_version: $(appveyor_build_version)
  assembly_version: $(appveyor_build_version)
  file_version: $(appveyor_build_version)
  informational_version: $(appveyor_build_version)
before_build:
  - ps: dotnet --version
build_script:
  - ps: dotnet build
test_script:
  - ps: dotnet test --test-adapter-path:. --logger:Appveyor
artifacts:
  - path: src\FluentCast\bin\Release\*.nupkg
    name: Nuget Package