version: '1.0.2.{build}'
image: Visual Studio 2017
configuration: Release
dotnet_csproj:
  patch: true
  file: 'src\FluentCast\FluentCast.csproj'
  version: '1.0.2'
  package_version: '1.0.2'
  assembly_version: '1.0.2'
  file_version: '1.0.2'
  informational_version: '1.0.2'
before_build:
  - ps: dotnet --version
build_script:
  - ps: dotnet build
test_script:
  - ps: dotnet test --test-adapter-path:. --logger:Appveyor
artifacts:
  - path: src\FluentCast\bin\Release\*.nupkg
    name: Nuget Package