version: 1.0.{build}
configuration: Release
build_script:
- ps: dotnet build
test_script:
- ps: dotnet test --test-adapter-path:. --logger:Appveyor
artifacts:
  - path: src\FluentCast\bin\Release\*.nupkg
    name: NuGet
deploy:
  - provider: NuGet
    name: production
    api_key:
      secure: oy2d3ki3icxmjrfl5b3qhzyy6kj73xeubjqaoj2jiltasy
    on:
      branch: master
      APPVEYOR_REPO_TAG: true