version: '{version}.{build}'
image: Visual Studio 2017
configuration: Release
dotnet_csproj:
  patch: true
  file: 'src\FluentCast\FluentCast.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
  - ps: dotnet --version
build_script:
  - ps: dotnet build
test_script:
  - ps: dotnet test --test-adapter-path:. --logger:Appveyor
artifacts:
  - path: src\FluentCast\bin\Release\*.nupkg
    name: Nuget Package